# Generated by Django 3.1.7 on 2021-06-27 14:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.DateField(max_length=100)),
                ('batch_std', models.IntegerField(choices=[(10, 10), (12, 12)])),
                ('batch_url', models.CharField(max_length=30)),
                ('batch_strength', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('batch_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_url', models.CharField(max_length=30)),
                ('school_propic', models.ImageField(upload_to='')),
                ('school_address_state', models.CharField(max_length=100)),
                ('school_address_district', models.CharField(max_length=100)),
                ('school_address_area', models.CharField(max_length=100)),
                ('School_description', models.CharField(max_length=300)),
                ('school_noof_batch', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_aka_name', models.CharField(max_length=30)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_password', models.CharField(max_length=30)),
                ('student_propic', models.ImageField(upload_to='')),
                ('student_description', models.CharField(max_length=300)),
                ('batch_reference_id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeMeet.batch')),
                ('school_reference_id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeMeet.school')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='school_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeMeet.school'),
        ),
    ]
