# Generated by Django 3.1.7 on 2021-08-25 11:43

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.DateField(max_length=100)),
                ('batch_std', models.IntegerField(choices=[(10, 10), (12, 12)])),
                ('batch_url', models.CharField(max_length=30)),
                ('batch_strength', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('batch_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_url', models.CharField(max_length=30)),
                ('school_propic', models.ImageField(upload_to='ProfilePicture/')),
                ('school_address_state', models.CharField(max_length=100)),
                ('school_address_district', models.CharField(max_length=100)),
                ('school_address_area', models.CharField(max_length=100)),
                ('School_description', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=30)),
                ('school_noof_batch', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_aka_name', models.CharField(max_length=30)),
                ('student_propic', models.ImageField(upload_to='ProfilePicture/')),
                ('student_std', models.IntegerField(choices=[(10, 10), (12, 12)])),
                ('student_url', models.CharField(max_length=30)),
                ('student_address_state', models.CharField(max_length=100)),
                ('student_address_district', models.CharField(max_length=100)),
                ('student_address_area', models.CharField(max_length=100)),
                ('student_description', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=30)),
                ('batch_reference_id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_batch', to='WeMeet.batch')),
                ('school_reference_id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='WeMeet.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='post/')),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=3000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('edited', models.BooleanField(default=False)),
                ('batch_reference_id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_batch', to='WeMeet.batch')),
                ('school_reference_id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_school', to='WeMeet.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_batch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='school_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_batch', to='WeMeet.school'),
        ),
    ]
