# Generated by Django 3.1.7 on 2021-06-28 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WeMeet', '0003_auto_20210628_1608'),
    ]

    operations = [

        migrations.AddField(
            model_name='student',
            name='student_std',
            field=models.IntegerField(choices=[(10, 10), (12, 12)], default='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='auth.user'),
            preserve_default=False,
        ),
    ]
