# Generated by Django 3.1.7 on 2021-07-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeMeet', '0004_auto_20210628_2322'),
    ]

    operations = [

        migrations.AlterField(
            model_name='school',
            name='school_propic',
            field=models.ImageField(upload_to='ProfilePicture/'),
        ),
 
        migrations.AlterField(
            model_name='student',
            name='student_propic',
            field=models.ImageField(upload_to='ProfilePicture/'),
        ),
    ]
