# Generated by Django 3.1.7 on 2021-07-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeMeet', '0005_auto_20210703_1427'),
    ]

    operations = [
 
        migrations.AddField(
            model_name='batch',
            name='batch_propic',
            field=models.ImageField(default='', upload_to='Batchprofile/'),
            preserve_default=False,
        )
    ]
