# Generated by Django 3.1.7 on 2021-07-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeMeet', '0007_auto_20210706_1318'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        
    ]
