# Generated by Django 3.1.7 on 2021-07-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeMeet', '0008_auto_20210718_1835'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='school',
            name='school_propic',
            field=models.ImageField(max_length=16383, upload_to='ProfilePicture/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_propic',
            field=models.ImageField(max_length=16383, upload_to='ProfilePicture/'),
        ),
    ]
