# Generated by Django 3.1.7 on 2021-07-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeMeet', '0009_auto_20210724_1223'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='batchchat',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        
    ]
