# Generated by Django 3.1.7 on 2021-07-28 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WeMeet', '0010_auto_20210728_0817'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='batchchat',
            name='user',
        ),
        migrations.AddField(
            model_name='batchchat',
            name='user',
            field=models.ManyToManyField(related_name='user_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
