# Generated by Django 3.1.7 on 2021-07-28 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WeMeet', '0011_auto_20210728_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=3000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('edited', models.BooleanField(default=False)),
                ('batch_reference_id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_batch', to='WeMeet.batch')),
                ('school_reference_id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_school', to='WeMeet.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_batch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
